version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - mongodb-network
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydatabase

  mongoexpress:
    image: mongo-express:latest
    restart: always
    networks:
      - mongodb-network
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb

  pizzeria-server:
    build: .
    environment:
      - MONGODB_URI=mongodb://username:password@mongodb:27017/mydatabase
      - SECRET=gmrja9IS6T9oegYieeRk7hJzAzeJ66PPWSmsMpmkFdA=

  nginx:
    image: nginx:latest
    restart: always
    networks:
      - mongodb-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key:ro
    ports:
      - '80:80'
      - '443:443'

networks:
  mongodb-network:
    driver: bridge

volumes:
  mongodb-data:
